---
# handlers file for libvirt

- name: restart libvirt
  become: yes
  service:
    name: "{{ libvirt_service_name }}"
    state: restarted
  tags:
    - libvirt

- name: reload libvirt
  become: yes
  service:
    name: "{{ libvirt_service_name }}"
    state: reloaded
  tags:
    - libvirt
