---
# handlers file for libvirt

- name: restart libvirt
  service:
    name: "{{ libvirt_services[0] }}"
    state: restarted
  when: libvirt_services

- name: reload libvirt
  service:
    name: "{{ libvirt_services[0] }}"
    state: reloaded
  when: libvirt_services
