---
dependency:
  name: galaxy
driver:
  name: docker

provisioner:
  name: ansible
  inventory:
    group_vars:
      no_libvirt_service:
        libvirt_services: []

platforms:
  - name: ansible-ubuntu-16-04-lts
    image: ubuntu:16.04
    groups:
      - no_libvirt_service
  - name: ansible-ubuntu-lts
    image: ubuntu:18.04
  - name: ansible-ubuntu-18-10
    image: ubuntu:18.10
    groups:
      - no_libvirt_service
  - name: ansible-debian
    image: debian:latest
  - name: ansible-arch
    image: archlinux/base:latest
    command: /usr/lib/systemd/systemd
    privileged: true
    groups:
      - no_libvirt_service
  - name: ansible-centos
    image: centos:latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
