---
dependency:
  name: galaxy
driver:
  name: docker

provisioner:
  name: ansible
  inventory:
    group_vars:
      no_libvirt_service:
        libvirt_services: []

platforms:
  - name: ansible-ubuntu-1604
    image: ubuntu
    image_version: '16.04'
    groups:
      - no_libvirt_service
  - name: ansible-ubuntu-1804
    image: ubuntu
    image_version: '18.04'
    groups:
      - no_libvirt_service
  - name: ansible-ubuntu-1810
    image: ubuntu
    image_version: '18.10'
    groups:
      - no_libvirt_service
  - name: ansible-debian
    image: debian
    image_version: 'latest'
  - name: ansible-arch
    image: archimg/base
    image_version: full
    command: /lib/systemd/systemd
    privileged: true
    groups:
      - no_libvirt_service
  - name: ansible-centos
    image: centos
    image_version: latest
    command: /usr/lib/systemd/systemd
    privileged: true

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
